### ISSUE TITLE
Material Not switching out

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/AniMix#109]
When the user switches to a new material on a **StopMotion** key, the material should hold for the duration of that keyframe. 
each new object should be able have any kind of materials stored with the object. This is for the classic idea of **ink and paint** purposes.

https://user-images.githubusercontent.com/16330340/217979252-7595096c-77a7-441b-98a8-117edeb2b869.mp4

**Comment by SuddenDevelopment** [comment]
this would be a new feature that is intentionally developed, but I thought we had it working by default before. are there cases it works vs not ?

**Comment by SuddenDevelopment** [comment]
Material swaps are in!
