### ISSUE TITLE
new  icons

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/AniMix#126]
Some new some revised icons based on feedback - I don't feel 100% about the spacing new  _add and remove space icons_
 let me know what your thoughts are. The change is more so to help the uer. I haven't worked out the text input for set space, help, please.
 
____
Preferences:
![image](https://user-images.githubusercontent.com/16330340/220964571-4816669a-f2b8-4d70-adf2-c544b64c62ee.png)

____
 NPanel:
 I'm still not happy with this one. Maybe drop the banner in last. To me the banner makes it to busy _(happy to have it just in preferences)_. We want to help the user get a good clear solid read to eliminate any confusion. Go right ahead and play with the ideas if you think you can get a better read on everything.
 
 I aslo notice the tooltips aren't hooked up to this yet. We will need to do that if we are going textless to explain the buttons. 
 
 ![image](https://user-images.githubusercontent.com/16330340/220949461-e651cf65-7d3f-478e-8f85-cf47ed9a38d4.png)

 
 ____
 **Viewport Panel:**
**Proposal 1**
![image](https://user-images.githubusercontent.com/16330340/220921208-4c1a79ec-491f-4702-96dc-8ea32dc1112c.png)

**Proposal 2**
![image](https://user-images.githubusercontent.com/16330340/220958735-81f0c9fa-5287-4350-ad2f-c42d7c135e93.png)

____
**Extra icons**
![3Dialogie](https://user-images.githubusercontent.com/16330340/220922522-c46cc5ab-ddd7-40f1-abe1-b6fc8d7748df.png)
![3Dialogie 32](https://user-images.githubusercontent.com/16330340/220923119-91919f30-945e-4340-823a-bfc90aeb1941.png)
![3Dialogie16 ](https://user-images.githubusercontent.com/16330340/220923162-c6f376fc-fb58-4c82-9335-32e38195f855.png)
![YouTube 44](https://user-images.githubusercontent.com/16330340/220926518-456aeac9-4081-493b-b3c3-fb1a187da184.png)
![YouTube 32](https://user-images.githubusercontent.com/16330340/220926582-3cd772cd-36d5-49b5-9687-b6aa85ec1ab1.png)
![YouTube 16](https://user-images.githubusercontent.com/16330340/220926621-6d5ba59f-c02e-445c-85dd-f3b09fb14b37.png)
![Bugs 16](https://user-images.githubusercontent.com/16330340/220948669-bad02a74-a41c-473e-b2da-da904fc65e48.png)
![Bugs 32](https://user-images.githubusercontent.com/16330340/220948674-744f9cf1-6c7a-4d94-a493-e2f3128dfc4e.png)
![Bugs 44](https://user-images.githubusercontent.com/16330340/220948679-f8008573-29f8-48bc-9851-ef874c985a80.png)
![AniMix Logo 16](https://user-images.githubusercontent.com/16330340/221091798-80e245fb-9795-4a0d-a36c-a1cdf031a3f3.png)

____
### 16 x 16
![Add To Asset Library](https://user-images.githubusercontent.com/16330340/220917604-0e0b6abe-dfdb-490a-a2ec-651de1b6677e.png)
![Asset Library](https://user-images.githubusercontent.com/16330340/220917641-31807b50-6548-4e0e-b111-e8bb252bdbe1.png)
![Combine With Active Object](https://user-images.githubusercontent.com/16330340/220918011-a5c85f91-9473-402a-9bec-430d92a992e2.png)
![Pin Frame Clear](https://user-images.githubusercontent.com/16330340/220918014-8c6dc83c-d01e-4fb2-afcd-c05af9a25711.png)
![Space Add](https://user-images.githubusercontent.com/16330340/220918020-a6c34a02-afd6-4a08-857e-19f05947c36d.png)
![Space None](https://user-images.githubusercontent.com/16330340/220918026-a1679fe0-e8c7-4ae4-9cba-853ab70395bf.png)
![Space Remove](https://user-images.githubusercontent.com/16330340/220918033-7f524fb8-9efd-498a-a4a9-7a18a2c9b0a6.png)
![Space Set](https://user-images.githubusercontent.com/16330340/220918042-b044d046-3262-4158-b87c-dde07247a077.png)

___
### 32 x 32
![Add To Asset Library](https://user-images.githubusercontent.com/16330340/220918444-65c71364-e2b9-4871-b25f-3192adb6af1d.png)
![Asset Library](https://user-images.githubusercontent.com/16330340/220918451-14ea608e-3847-474c-9a2c-69929c737d52.png)
![Combine With Active Object](https://user-images.githubusercontent.com/16330340/220918453-1889bb12-de1f-428b-81e4-8c0968547e5f.png)
![Pin Frame Clear](https://user-images.githubusercontent.com/16330340/220918457-4a591ec1-5029-4ced-8f07-5aa50a76d9b3.png)
![Space Add Half Button](https://user-images.githubusercontent.com/16330340/220918462-56fbbb6e-e955-41f1-a0ff-91bd04b66739.png)
![Space Add](https://user-images.githubusercontent.com/16330340/220918464-1d2cb5b3-e36c-429e-9f8d-950fc4384113.png)
![Space Non Half Button](https://user-images.githubusercontent.com/16330340/220918469-b90efb28-db0d-4d63-91d5-503fb54b3b96.png)
![Space None](https://user-images.githubusercontent.com/16330340/220918474-f09207e2-a9a9-4e93-992c-a5fab3083032.png)
![Space Remove Half Button](https://user-images.githubusercontent.com/16330340/220918478-3f958cd0-0a39-4599-b0d0-1005f6a5e84f.png)
![Space Remove](https://user-images.githubusercontent.com/16330340/220918485-e326cfc6-2353-495b-b5cd-fbe4278f6b5a.png)
![Space Set Half Button](https://user-images.githubusercontent.com/16330340/220918489-4a536f0b-f113-400d-ae2d-298cbbbabd9e.png)
![Space Set](https://user-images.githubusercontent.com/16330340/220918494-6faa4eab-b1db-4004-a74a-54fcc54f515a.png)

___
### 44 x 44
![Combine With Active Object](https://user-images.githubusercontent.com/16330340/220918916-3ef5417f-264a-4d0c-a7aa-5584526f957f.png)
![Pin Frame Clear](https://user-images.githubusercontent.com/16330340/220918920-68af75da-4b53-4f70-8b88-8a772a089b3a.png)
![Space Add Half Button](https://user-images.githubusercontent.com/16330340/220918926-783c5b17-e512-4397-b73d-d3c36d71c2eb.png)
![Space Add](https://user-images.githubusercontent.com/16330340/220918929-45745a74-0117-4e12-813f-232a8fc972a6.png)
![Space Non Half Button](https://user-images.githubusercontent.com/16330340/220918931-3ccace66-3ba4-4995-bbc7-6dd98698f01d.png)
![Space None](https://user-images.githubusercontent.com/16330340/220918932-3d97c2a3-9a99-4be7-a056-655b54f2d84b.png)
![Space Remove Half Button](https://user-images.githubusercontent.com/16330340/220918935-b64e4fb3-4572-4051-9074-23378be43cd2.png)
![Space Remove](https://user-images.githubusercontent.com/16330340/220918937-5eccccb8-06c8-4be3-85a7-dd9298797d90.png)
![Space Set Half Button](https://user-images.githubusercontent.com/16330340/220918941-5fcef4d0-9e17-4cb2-aaf4-2c36cd2729e6.png)
![Space Set](https://user-images.githubusercontent.com/16330340/220918946-2cb783c1-cefc-4b47-b484-7d5f7c33d42a.png)
![Add To Asset Library](https://user-images.githubusercontent.com/16330340/220918903-fcf14c64-ef33-4fec-9a98-5a7cd10229b8.png)
![Asset Library](https://user-images.githubusercontent.com/16330340/220918912-46b40582-c662-4e9d-a68d-e209b344040e.png)

**Comment by SuddenDevelopment** [comment]
done
