### ISSUE TITLE
Icon Fix

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/AniMix#128]
nPanel switch the **Add Remove Space** icons

![Space Add](https://user-images.githubusercontent.com/16330340/221441880-61d92dde-a93c-4bdd-a351-92c7b899d843.png)
![Space Remove](https://user-images.githubusercontent.com/16330340/221441881-9238ae49-84a2-4976-81c7-2240e8ce17bd.png)

Set icon to be on the same row as  **Space settings**

**Comment by SuddenDevelopment** [comment]
![Screenshot 2023-02-27 at 2 54 11 PM](https://user-images.githubusercontent.com/138704/221668748-f0ccd845-9697-4bff-9a41-295b791b0ffe.png)
done
