### ISSUE TITLE
Viewport panel

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/AniMix#129]
Add Remove Space Icons
![Space Remove Half Button](https://user-images.githubusercontent.com/16330340/221442075-7ff6269e-d5e7-49c3-bf29-189cfe46e436.png)
![Space Add Half Button](https://user-images.githubusercontent.com/16330340/221442076-e3e36988-9e38-489a-8511-06269651db15.png)

Set Space
![Space Set Half Button](https://user-images.githubusercontent.com/16330340/221442129-6b7cb82b-b30e-479a-aa53-2b0b7a30d56a.png)

**Comment by SuddenDevelopment** [comment]
![Screenshot 2023-02-27 at 3 14 12 PM](https://user-images.githubusercontent.com/138704/221673460-6a64be12-6119-443b-9479-089c48105b91.png)
