### ISSUE TITLE
StopMotion Key Update When leaving Edit mode

### ISSUE THREAD

**Issue by adamearle** [SuddenDevelopment/AniMix#99]
key are only committed in edit mode once the playhead has been moved.
if the play doesn't move in edit mode and the user enters object mode the drawings will be lost.

https://user-images.githubusercontent.com/16330340/216883111-a82b2de9-8f31-40d1-b027-33c722d2474d.mp4

**Comment by SuddenDevelopment** [comment]
yep, the trigger is onFrame in edit mode.
in Object mode need to hit overwrite / insert the key

I can look for how to trigger on the mode change, I'm not aware of one yet. May need to be a known issue

**Comment by adamearle** [comment]
Leave it till last
